import { styling } from "./globals.css";
import { Footer, Navbar } from "@/components/index";
import { Toaster } from "sonner";

export const metadata = {
  title: "Mamarecipe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
